### ISSUE TITLE
Image view

### ISSUE THREAD

**Issue by jose4n** [KChen89/Heartbeat-Classification-based-Diagnosis#1]
Hi,
After run this : python3 hb_classifier.py ecg.dat just says Time cost:  0.3077363967895508
Is there any way to se the result  like demo screenshots?

**Comment by KChen89** [comment]
The screenshot is produced by running the code on my computer (Lubuntu
14.04 LTS). Also check if ​code for plotting is executed (figures created at plt.show()) and your backend following the link https://stackoverflow.com/questions/14558843/why-matplotlib-does-not-plot.
Good luck,
K.C.



jose4n <notifications@github.com> 于 2018年5月19日 周六 11:15写道：

**Comment by jose4n** [comment]
Thanks!!
I just replaced plt.show() by plt.savefig('name.png') and worked perfectly.
